'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AGENDAMENTO
    
    '''<summary>
    '''MensagemERRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MensagemERRO As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''CaixaRemocao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaixaRemocao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Titulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Titulo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''cmdVoltar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdVoltar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TabelaPolos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabelaPolos As Global.System.Web.UI.WebControls.Table
End Class
