'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PerguntasTurma
    
    '''<summary>
    '''MensagemERRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MensagemERRO As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''CampoTurma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CampoTurma As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''CampoCO_CENSO_TURMA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CampoCO_CENSO_TURMA As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTotalTurma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalTurma As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbHorario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbHorario As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbHorario2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbHorario2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''divcontroles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divcontroles As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PasswordLabel33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordLabel33 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UserNameLabel29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel29 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UserNameLabel30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel30 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UserNameLabel31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel31 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PasswordLabel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordLabel24 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPrevistos1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrevistos1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UserNameLabel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel11 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbConfirmados1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbConfirmados1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''UserNameLabel32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel32 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbNaoPrev10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbNaoPrev10 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''PasswordLabel25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordLabel25 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPrevistos2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrevistos2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UserNameLabel33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel33 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbConfirmados2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbConfirmados2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''UserNameLabel34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel34 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbNaoPrev9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbNaoPrev9 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''PasswordLabel26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordLabel26 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPrevistos3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrevistos3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UserNameLabel35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel35 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbConfirmados3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbConfirmados3 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''UserNameLabel36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel36 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbNaoPrev11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbNaoPrev11 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''PasswordLabel27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordLabel27 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPrevistos4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrevistos4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UserNameLabel37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel37 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbConfirmados4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbConfirmados4 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''UserNameLabel38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel38 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PasswordLabel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordLabel28 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPrevistos6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrevistos6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UserNameLabel39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel39 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbConfirmados6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbConfirmados6 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''UserNameLabel40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel40 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PasswordLabel29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordLabel29 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UserNameLabel41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel41 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UserNameLabel42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel42 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbNaoPrev4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbNaoPrev4 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''PasswordLabel30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordLabel30 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UserNameLabel43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel43 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UserNameLabel44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel44 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbNaoPrev6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbNaoPrev6 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''PasswordLabel31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordLabel31 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPrevistos5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrevistos5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UserNameLabel45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel45 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbConfirmados5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbConfirmados5 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''UserNameLabel46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel46 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbNaoPrev5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbNaoPrev5 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''PasswordLabel32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordLabel32 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPrevistos7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrevistos7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''UserNameLabel47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel47 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbConfirmados7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbConfirmados7 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''UserNameLabel48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel48 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbNaoPrev7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbNaoPrev7 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''UserNameLabel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameLabel28 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmdEntrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEntrar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCancelar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LabelIncAlt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelIncAlt As Global.System.Web.UI.WebControls.Label
End Class
