'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class POLOS
    
    '''<summary>
    '''PainelBuscas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PainelBuscas As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Bandeirinha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Bandeirinha As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''LabelUF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelUF As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbUF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbUF As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LabelMunicipio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelMunicipio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbMunicipio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbMunicipio As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CampoFiltroBusca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CampoFiltroBusca As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmdBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdBuscar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cmdVoltar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdVoltar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmRetroceder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmRetroceder As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cmbPaginas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPaginas As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmdAvancar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAvancar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelPolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPolo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbPolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPolo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LabelEscola control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelEscola As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbEscola control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbEscola As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LabelFuncao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelFuncao As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbFuncao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFuncao As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LabelStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LabelCategoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCategoria As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbCategoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCategoria As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''MensagemERROS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MensagemERROS As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''LiteralNumLinhas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralNumLinhas As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''CaixaRemocao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaixaRemocao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Titulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Titulo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''TabelaPolos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabelaPolos As Global.System.Web.UI.WebControls.Table
End Class
